### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by nubonics** [TETYYS/LiveProxies#5]
nubonix@desktopzero:/opt/LiveProxies$ make
[  5%] Linking C executable LiveProxies
/usr/bin/ld: CMakeFiles/LiveProxies.dir/LiveProxies.c.o: in function `main':
/opt/LiveProxies/LiveProxies.c:210: undefined reference to `evthread_use_pthreads'
/usr/bin/ld: CMakeFiles/LiveProxies.dir/ProxyRequest.c.o: in function `ProxyHandleData':
/opt/LiveProxies/ProxyRequest.c:958: undefined reference to `bufferevent_openssl_get_ssl'
/usr/bin/ld: /opt/LiveProxies/ProxyRequest.c:935: undefined reference to `bufferevent_openssl_socket_new'
/usr/bin/ld: CMakeFiles/LiveProxies.dir/Server.c.o: in function `ServerAccept':
/opt/LiveProxies/Server.c:489: undefined reference to `bufferevent_openssl_socket_new'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/LiveProxies.dir/build.make:354: LiveProxies] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/LiveProxies.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by TETYYS** [comment]
sorry, this is no longer maintained..
